package com.repoinsight.model;

import java.util.ArrayList;
import java.util.List;

/**
 * A prioritized recommendation generated by the recommendation engine.
 */
public class Recommendation {

    public enum Priority { P0, P1, P2, P3 }
    public enum Category {
        MISSING_COVERAGE, NEGATIVE_PATH_GAP, BOUNDARY_GAP, SECURITY_GAP,
        INTEGRATION_GAP, DUPLICATE_TEST, OBSOLETE_TEST, WEAK_TRACEABILITY,
        ARCHITECTURE, DOCUMENTATION, TEST_DESIGN
    }

    private String id;
    private String title;
    private String description;
    private Priority priority;
    private Feature.Severity severity;
    private Category category;
    private String businessImpact;
    private String rationale;
    private List<EvidenceLink> evidenceLinks = new ArrayList<>();
    private List<String> suggestedTestTypes = new ArrayList<>();
    private boolean aiEnriched;

    public Recommendation() {}

    // ── Getters / Setters ─────────────────────────────────────────────────────

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public Priority getPriority() { return priority; }
    public void setPriority(Priority priority) { this.priority = priority; }
    public Feature.Severity getSeverity() { return severity; }
    public void setSeverity(Feature.Severity severity) { this.severity = severity; }
    public Category getCategory() { return category; }
    public void setCategory(Category category) { this.category = category; }
    public String getBusinessImpact() { return businessImpact; }
    public void setBusinessImpact(String businessImpact) { this.businessImpact = businessImpact; }
    public String getRationale() { return rationale; }
    public void setRationale(String rationale) { this.rationale = rationale; }
    public List<EvidenceLink> getEvidenceLinks() { return evidenceLinks; }
    public void setEvidenceLinks(List<EvidenceLink> evidenceLinks) { this.evidenceLinks = evidenceLinks; }
    public List<String> getSuggestedTestTypes() { return suggestedTestTypes; }
    public void setSuggestedTestTypes(List<String> suggestedTestTypes) { this.suggestedTestTypes = suggestedTestTypes; }
    public boolean isAiEnriched() { return aiEnriched; }
    public void setAiEnriched(boolean aiEnriched) { this.aiEnriched = aiEnriched; }
}
